SELECT 
200                                             AS MANDT,
3000                                            AS EMPRESA,
Supplier.externalCode                           AS FILIAL,
N                                               AS ID,
                                                AS DT_REGISTRO,
                                                AS TOT_VS
                                                AS TOT_ISS
                                                AS TOT_OUTROS             
FROM